### ISSUE TITLE
Can't Enter Windows system

### ISSUE THREAD

**Issue by Float-004** [wxjiyc/CHUWI-CoreBook-X-2022-8259U-Hackintosh#1]
01. But I can't enter the Windows system. I think it is the problem of the DSDT patch in ACPI. Is there any solution? Thanks!

**Comment by wxjiyc** [comment]
> 1. But I can't enter the Windows system. I think it is the problem of the DSDT patch in ACPI. Is there any solution? Thanks!

Thanks for your attention. This version is only applicable to the new version of CHUWI CoreBook X (SN:JCorB...... Memory:16GB single channel), but the EFI is still under testing. It is unstable and I will continue to update.Can you tell me your blue screen error code?

**Comment by Float-004** [comment]
> 



> > 1. But I can't enter the Windows system. I think it is the problem of the DSDT patch in ACPI. Is there any solution? Thanks!
> 
> Thanks for your attention. This version is only applicable to the new version of CHUWI CoreBook X (SN:JCorB...... Memory:16GB single channel), but the EFI is still under testing. It is unstable and I will continue to update.Can you tell me your blue screen error code?

I'm sure my computer is this version and this is the blue screen code.
![WechatIMG147](https://user-images.githubusercontent.com/73101368/151173604-beac53ef-50e2-4ca2-b40b-9261da3a0206.jpeg)

**Comment by wxjiyc** [comment]
> > 
> 
> > > 1. But I can't enter the Windows system. I think it is the problem of the DSDT patch in ACPI. Is there any solution? Thanks!
> > 
> > 
> > Thanks for your attention. This version is only applicable to the new version of CHUWI CoreBook X (SN:JCorB...... Memory:16GB single channel), but the EFI is still under testing. It is unstable and I will continue to update.Can you tell me your blue screen error code?
> 
> I'm sure my computer is this version and this is the blue screen code. ![WechatIMG147](https://user-images.githubusercontent.com/73101368/151173604-beac53ef-50e2-4ca2-b40b-9261da3a0206.jpeg)

暂时用bios菜单引导吧，目前为了解决电池状态问题，我没做热补丁，所以会有这问题，最近比较忙，我后续会更新

**Comment by Float-004** [comment]
> > > 
> > 
> > 
> > > > 1. But I can't enter the Windows system. I think it is the problem of the DSDT patch in ACPI. Is there any solution? Thanks!
> > > 
> > > 
> > > Thanks for your attention. This version is only applicable to the new version of CHUWI CoreBook X (SN:JCorB...... Memory:16GB single channel), but the EFI is still under testing. It is unstable and I will continue to update.Can you tell me your blue screen error code?
> > 
> > 
> > I'm sure my computer is this version and this is the blue screen code. ![WechatIMG147](https://user-images.githubusercontent.com/73101368/151173604-beac53ef-50e2-4ca2-b40b-9261da3a0206.jpeg)
> 
> 暂时用bios菜单引导吧，目前为了解决电池状态问题，我没做热补丁，所以会有这问题，最近比较忙，我后续会更新

好的！

**Comment by hyperzlib** [comment]
你也可以试试通过grub做引导菜单，grub支持加载指定efi文件，写个引导windows和opencore的efi的启动项就行了

**Comment by wxjiyc** [comment]
Bug fixed
