### ISSUE TITLE
No battery Percentage/Status Monterey

### ISSUE THREAD

**Issue by ivancaas** [wxjiyc/CHUWI-CoreBook-X-2022-8259U-Hackintosh#4]
i've installed Monterey 12.3 with this EFI(no success until i've added all drivers from the OpenCore default package...) but... SMCBatteryManager says "failed to find bateries or adapters". Any Solution? I've tried disabling that kext, but maybe i need some patching? Thanks!

**Comment by phaberest** [comment]
I'm on the same boat, I even tried starting all over from Clover example copying and adapting from this EFI and I can't find a way to get the battery status to work.

In addition to this, the trackpad keeps opening the force touch quick look (as example dictionary) and the CPU si seen as i7 quad core in the "About this mac" info

**Comment by ivancaas** [comment]
> I'm on the same boat, I even tried starting all over from Clover example copying and adapting from this EFI and I can't find a way to get the battery status to work.
> 
> In addition to this, the trackpad keeps opening the force touch quick look (as example dictionary) and the CPU si seen as i7 quad core in the "About this mac" info

I've installed the system with this EFI(with all the drivers from vanilla opencore) and i reach battery working with another repo: https://github.com/terminet85/CoreBook_X_Gen8_JCorB_OC, try to change only your EFI with this(ive populated the drivers folder here too for the doubts xD) 

With this EFI i've mid-solved the Trackpad force touch problem, changing some options in the Kext plist of the Vodoo

**Comment by phaberest** [comment]
Thank you @ivancaas, I had just discovered https://github.com/rboldini/CoreBook_X_OC/issues/11 and did the same, even tho I'm as well still dealing with the trackpad problem and it sounds like the kexts order in config.plist could be part of the issue

**Comment by wxjiyc** [comment]
I've fixed the battery issue: [SSDT-ADP-BAT.aml](https://github.com/wxjiyc/CHUWI-CoreBook-X-2022-8259U-Hackintosh/blob/main/EFI/OC/ACPI/SSDT-ADP-BAT.aml) and https://github.com/wxjiyc/CHUWI-CoreBook-X-2022-8259U-Hackintosh/blob/5b21e17a6829e22c2c05ee45bc4ec5f907ef971a/EFI/OC/config.plist#L204, please check if your serial number starts with "JCorB..."

**Comment by wxjiyc** [comment]
Maybe there are some differences in our BIOS, different DSDTs may cause the patch to fail

**Comment by phaberest** [comment]
Thank you @wxjiyc, the serial starts indeed with `JCorB`

Yeah, I'm going to use the debug version of the kexts to check the logs and (try to) sort out what's wrong
