### ISSUE TITLE
请教一下驰为这款型号的相关问题

### ISSUE THREAD

**Issue by MokouTyan** [wxjiyc/CHUWI-CoreBook-X-2022-8259U-Hackintosh#5]
1.黑苹果后听说风扇很响，是因为调速吗？
2.黑苹果后的续航长短
3.有没有合盖睡眠，开盖自动唤醒的相关功能
肥肠感谢分享efi~

**Comment by wxjiyc** [comment]
> 1.黑苹果后听说风扇很响，是因为调速吗？ 2.黑苹果后的续航长短 3.有没有合盖睡眠，开盖自动唤醒的相关功能 肥肠感谢分享efi~

1. EC温控策略，对温度比较敏感
2. 和win下差不多
3. 有，正常
